spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa1;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org.hibernate.sql: warn
    #org.hibernate.type: trace